In [1]:
import pandas as pd
from datetime import datetime
from tqdm import tqdm

In [2]:
start = datetime.now()
df_fundq_raw = pd.read_csv("data/fundq_NA_202308.csv")
end = datetime.now()
print(end - start)

C:\Users\Marlow\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (10,12,13,17,18,20,25,26,30,32,33,34,35,647,648,649,650,654,656,657,664,668,669,674,675,677,678,679) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

0:01:25.716751

In [3]:
print("Get unique values from specified column:\n", df_fundq_raw['loc'].unique())

Get unique values from specified column:
 ['USA' 'CAN' 'NLD' 'ISR' 'HKG' 'BMU' 'CHN' 'TWN' 'PHL' 'GBR' 'ESP' 'FRA'
 'ZWE' 'JPN' 'DEU' 'DNK' 'SGP' 'ARE' 'PAN' 'BEL' 'IRL' 'SWE' 'POL' 'AUS'
 'MEX' 'FIN' 'CHE' 'BHS' 'KOR' 'BGD' 'NOR' 'ZAF' 'BHR' 'ANT' 'SLV' 'CYM'
 'CZE' 'ITA' 'ZMB' 'LUX' 'CRI' 'NZL' 'NGA' 'BOL' 'MCO' 'VGB' 'GRC' 'IND'
 'THA' 'BLZ' 'CYP' 'PER' 'BRA' 'MHL' 'MYS' 'CHL' 'PRT' 'VEN' 'HUN' 'JEY'
 'ARG' 'KAZ' 'AUT' 'HND' 'IDN' 'TUR' 'COL' 'RUS' 'JOR' 'GGY' 'ISL' 'GIB'
 'URY' 'MAC' 'NIC' 'PNG' 'MUS' 'DOM' 'BRB' 'TTO' 'UKR' 'ECU' 'JAM' 'BGR'
 'IMN' 'GHA' 'VIR']

In [4]:
df_fundq_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1966037 entries, 0 to 1966036
Columns: 680 entries, gvkey to ipodate
dtypes: float64(627), int64(5), object(48)
memory usage: 10.0+ GB

In [5]:
df_fundq_raw = df_fundq_raw[df_fundq_raw['loc'] == 'USA']

In [6]:
print("Get unique values from specified column:\n", df_fundq_raw['loc'].unique())

Get unique values from specified column:
 ['USA']

In [7]:
df_fundq_raw.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1596856 entries, 0 to 1966036
Columns: 680 entries, gvkey to ipodate
dtypes: float64(627), int64(5), object(48)
memory usage: 8.1+ GB

In [8]:
df_fundq_raw

,gvkey,datadate,fyearq,fqtr,fyr,indfmt,consol,popsrc,datafmt,tic,...,priusa,sic,spcindcd,spcseccd,spcsrc,state,stko,weburl,dldte,ipodate
0,1000,1966-03-31,1966,1.0,12,INDL,C,D,STD,AE.2,...,1.0,3089,325.0,978.0,NaN,NaN,0.0,NaN,1978-06-30,NaN
1,1000,1966-06-30,1966,2.0,12,INDL,C,D,STD,AE.2,...,1.0,3089,325.0,978.0,NaN,NaN,0.0,NaN,1978-06-30,NaN
2,1000,1966-09-30,1966,3.0,12,INDL,C,D,STD,AE.2,...,1.0,3089,325.0,978.0,NaN,NaN,0.0,NaN,1978-06-30,NaN
3,1000,1966-12-31,1966,4.0,12,INDL,C,D,STD,AE.2,...,1.0,3089,325.0,978.0,NaN,NaN,0.0,NaN,1978-06-30,NaN
4,1000,1967-03-31,1967,1.0,12,INDL,C,D,STD,AE.2,...,1.0,3089,325.0,978.0,NaN,NaN,0.0,NaN,1978-06-30,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1965983,351038,2022-12-31,2022,4.0,12,INDL,C,D,STD,QNRX,...,90.0,2834,NaN,NaN,NaN,VA,0.0,quoinpharma.com,NaN,NaN
1965984,351038,2023-03-31,2023,1.0,12,INDL,C,D,STD,QNRX,...,90.0,2834,NaN,NaN,NaN,VA,0.0,quoinpharma.com,NaN,NaN
1965985,351038,2023-06-30,2023,2.0,12,INDL,C,D,STD,QNRX,...,90.0,2834,NaN,NaN,NaN,VA,0.0,quoinpharma.com,NaN,NaN
1966035,354003,2023-03-31,2023,1.0,12,INDL,C,D,STD,BEMB,...,1.0,6722,NaN,NaN,NaN,CA,NaN,www.ishares.com,NaN,NaN
1966036,354003,2023-06-30,2023,2.0,12,INDL,C,D,STD,BEMB,...,1.0,6722,NaN,NaN,NaN,CA,NaN,www.ishares.com,NaN,NaN

In [9]:
df_fundq_raw = df_fundq_raw.drop_duplicates(subset=['gvkey', 'datadate'], keep='first')

In [10]:
df_fundq_raw.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1595737 entries, 0 to 1966036
Columns: 680 entries, gvkey to ipodate
dtypes: float64(627), int64(5), object(48)
memory usage: 8.1+ GB

In [11]:
df_fundq_raw = df_fundq_raw[df_fundq_raw['fyearq'] >= 1989]
df_fundq_raw = df_fundq_raw[df_fundq_raw['fyearq'] <= 2020]
df_fundq_raw.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1118711 entries, 90 to 1965975
Columns: 680 entries, gvkey to ipodate
dtypes: float64(627), int64(5), object(48)
memory usage: 5.7+ GB

In [12]:
df_fundq_raw

,gvkey,datadate,fyearq,fqtr,fyr,indfmt,consol,popsrc,datafmt,tic,...,priusa,sic,spcindcd,spcseccd,spcsrc,state,stko,weburl,dldte,ipodate
90,1003,1989-04-30,1989,1.0,1,INDL,C,D,STD,ANTQ,...,1.0,5712,449.0,976.0,NaN,MO,3.0,www.aaimporting.com,1992-04-30,NaN
91,1003,1989-07-31,1989,2.0,1,INDL,C,D,STD,ANTQ,...,1.0,5712,449.0,976.0,NaN,MO,3.0,www.aaimporting.com,1992-04-30,NaN
92,1003,1989-10-31,1989,3.0,1,INDL,C,D,STD,ANTQ,...,1.0,5712,449.0,976.0,NaN,MO,3.0,www.aaimporting.com,1992-04-30,NaN
93,1003,1990-01-31,1989,4.0,1,INDL,C,D,STD,ANTQ,...,1.0,5712,449.0,976.0,NaN,MO,3.0,www.aaimporting.com,1992-04-30,NaN
94,1003,1990-04-30,1990,1.0,1,INDL,C,D,STD,ANTQ,...,1.0,5712,449.0,976.0,NaN,MO,3.0,www.aaimporting.com,1992-04-30,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1965872,345980,2020-12-31,2020,4.0,12,INDL,C,D,STD,WISH,...,1.0,5961,NaN,NaN,NaN,CA,0.0,www.wish.com,NaN,2020-12-16
1965972,351038,2020-03-31,2020,1.0,12,INDL,C,D,STD,QNRX,...,90.0,2834,NaN,NaN,NaN,VA,0.0,quoinpharma.com,NaN,NaN
1965973,351038,2020-06-30,2020,2.0,12,INDL,C,D,STD,QNRX,...,90.0,2834,NaN,NaN,NaN,VA,0.0,quoinpharma.com,NaN,NaN
1965974,351038,2020-09-30,2020,3.0,12,INDL,C,D,STD,QNRX,...,90.0,2834,NaN,NaN,NaN,VA,0.0,quoinpharma.com,NaN,NaN
1965975,351038,2020-12-31,2020,4.0,12,INDL,C,D,STD,QNRX,...,90.0,2834,NaN,NaN,NaN,VA,0.0,quoinpharma.com,NaN,NaN

In [13]:
# df_fundq_raw.to_csv("data/raw_data_with_timecutoffs")

start = datetime.now()
df_fundq_raw[['cshoq', 'prccq', 'cshpry', 'epsfiy', 'epspxy', 'ibcomy', 'iby', 'niy', 'nopiy', 'oiadpy', 'saley', 'oibdpq', 'dpq', 'saleq']] = df_fundq_raw[['cshoq', 'prccq', 'cshpry', 'epsfiy', 'epspxy', 'ibcomy', 'iby', 'niy', 'nopiy', 'oiadpy', 'saley', 'oibdpq', 'dpq', 'saleq']].interpolate()
end = datetime.now()
print(end - start)

0:00:01.494920

In [14]:
df_fundq_raw

,gvkey,datadate,fyearq,fqtr,fyr,indfmt,consol,popsrc,datafmt,tic,...,priusa,sic,spcindcd,spcseccd,spcsrc,state,stko,weburl,dldte,ipodate
90,1003,1989-04-30,1989,1.0,1,INDL,C,D,STD,ANTQ,...,1.0,5712,449.0,976.0,NaN,MO,3.0,www.aaimporting.com,1992-04-30,NaN
91,1003,1989-07-31,1989,2.0,1,INDL,C,D,STD,ANTQ,...,1.0,5712,449.0,976.0,NaN,MO,3.0,www.aaimporting.com,1992-04-30,NaN
92,1003,1989-10-31,1989,3.0,1,INDL,C,D,STD,ANTQ,...,1.0,5712,449.0,976.0,NaN,MO,3.0,www.aaimporting.com,1992-04-30,NaN
93,1003,1990-01-31,1989,4.0,1,INDL,C,D,STD,ANTQ,...,1.0,5712,449.0,976.0,NaN,MO,3.0,www.aaimporting.com,1992-04-30,NaN
94,1003,1990-04-30,1990,1.0,1,INDL,C,D,STD,ANTQ,...,1.0,5712,449.0,976.0,NaN,MO,3.0,www.aaimporting.com,1992-04-30,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1965872,345980,2020-12-31,2020,4.0,12,INDL,C,D,STD,WISH,...,1.0,5961,NaN,NaN,NaN,CA,0.0,www.wish.com,NaN,2020-12-16
1965972,351038,2020-03-31,2020,1.0,12,INDL,C,D,STD,QNRX,...,90.0,2834,NaN,NaN,NaN,VA,0.0,quoinpharma.com,NaN,NaN
1965973,351038,2020-06-30,2020,2.0,12,INDL,C,D,STD,QNRX,...,90.0,2834,NaN,NaN,NaN,VA,0.0,quoinpharma.com,NaN,NaN
1965974,351038,2020-09-30,2020,3.0,12,INDL,C,D,STD,QNRX,...,90.0,2834,NaN,NaN,NaN,VA,0.0,quoinpharma.com,NaN,NaN
1965975,351038,2020-12-31,2020,4.0,12,INDL,C,D,STD,QNRX,...,90.0,2834,NaN,NaN,NaN,VA,0.0,quoinpharma.com,NaN,NaN

In [15]:
start = datetime.now()
df_fundq_raw['mkvaltq'] = df_fundq_raw.groupby(['gvkey', 'fyearq'], group_keys=False)['cshoq'].apply(lambda x: x * df_fundq_raw.loc[x.index, 'prccq'].values[0])
end = datetime.now()
print(end - start)

0:01:21.707175

In [16]:
start = datetime.now()
df_fundq_raw[['q_cshpry', 'q_epsfiy', 'q_epspxy', 'q_ibcomy', 'q_iby', 'q_niy', 'q_nopiy', 'q_oiadpy', 'q_saley']] = df_fundq_raw.groupby(['gvkey', 'fyearq'], group_keys=False)[['cshpry', 'epsfiy', 'epspxy', 'ibcomy', 'iby', 'niy', 'nopiy', 'oiadpy', 'saley']].apply(lambda x: x - x.shift(1))
end = datetime.now()
print(end - start)

0:01:32.992099

In [17]:
start = datetime.now()
df_fundq_raw[['nopatq']] = df_fundq_raw.groupby(['gvkey', 'fyearq'], group_keys=False)[['oibdpq']].apply(lambda x: x * 0.65)
end = datetime.now()
print(end - start)

0:01:02.693329

In [18]:
start = datetime.now()
df_fundq_raw[['dep']] = df_fundq_raw.groupby(['gvkey', 'fyearq'], group_keys=False)['dpq'].apply(lambda x: x / df_fundq_raw.loc[x.index, 'saleq'].values[0])
end = datetime.now()
print(end - start)

0:01:23.090751

In [19]:
start = datetime.now()
df_fundq_raw[['pm']] = df_fundq_raw.groupby(['gvkey', 'fyearq'], group_keys=False)['oibdpq'].apply(lambda x: x / df_fundq_raw.loc[x.index, 'saleq'].values[0])
end = datetime.now()
print(end - start)

0:01:25.950251

In [20]:
df_fundq_raw

,gvkey,datadate,fyearq,fqtr,fyr,indfmt,consol,popsrc,datafmt,tic,...,q_epspxy,q_ibcomy,q_iby,q_niy,q_nopiy,q_oiadpy,q_saley,nopatq,dep,pm
90,1003,1989-04-30,1989,1.0,1,INDL,C,D,STD,ANTQ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,1003,1989-07-31,1989,2.0,1,INDL,C,D,STD,ANTQ,...,0.1500,-0.01875,0.41500,2.74800,0.0000,-0.7550,4.384,NaN,NaN,NaN
92,1003,1989-10-31,1989,3.0,1,INDL,C,D,STD,ANTQ,...,-0.2200,-0.01875,-0.61300,-0.61300,0.0000,-0.4750,4.776,NaN,NaN,NaN
93,1003,1990-01-31,1989,4.0,1,INDL,C,D,STD,ANTQ,...,-0.6000,-0.01875,-1.60300,-1.60300,-0.9000,-0.5690,4.913,NaN,NaN,NaN
94,1003,1990-04-30,1990,1.0,1,INDL,C,D,STD,ANTQ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1965872,345980,2020-12-31,2020,4.0,12,INDL,C,D,STD,WISH,...,-0.9700,-569.00000,-569.00000,-569.00000,-57.0000,-511.0000,794.000,-330.200000,0.006818,-1.154545
1965972,351038,2020-03-31,2020,1.0,12,INDL,C,D,STD,QNRX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-247.904475,0.003822,-0.640456
1965973,351038,2020-06-30,2020,2.0,12,INDL,C,D,STD,QNRX,...,0.1425,185.72625,185.72625,185.72625,27.9055,157.3325,-635.250,-165.608950,0.002606,-0.427847
1965974,351038,2020-09-30,2020,3.0,12,INDL,C,D,STD,QNRX,...,0.1425,185.72625,185.72625,185.72625,27.9055,157.3325,-635.250,-83.313425,0.001390,-0.215238
1965975,351038,2020-12-31,2020,4.0,12,INDL,C,D,STD,QNRX,...,0.1425,185.72625,185.72625,185.72625,27.9055,157.3325,-635.250,-1.017900,0.000175,-0.002630

In [21]:
# Liste der Spalten, die kopiert werden sollen
columns_to_copy = ['gvkey', 'fyearq', 'fqtr', 'atq', 'saleq', 'mkvaltq', 'ibcomq', 'oiadpq', 'prccq', 'prchq', 'prclq', 'apq', 'capsq', 'cheq', 'csh12q', 'cshfdq', 'cshoq', 'cshprq', 'cshtrq', 'cstkq', 'dpq', 'dvpq', 'dvpsxq', 'epsf12', 'epsfiq', 'epsfxq', 'epspiq', 'epspxq', 'epsx12', 'ibq', 'icaptq', 'loq', 'lseq', 'ltq', 'mibq', 'mibtq', 'miiq', 'ncoq', 'niq', 'nopiq', 'oibdpq', 'piq', 'pllq', 'ppentq', 'pstkq', 'rectq', 'req', 'rllq', 'saleq', 'seqq', 'teqq', 'tieq', 'txtq', 'xidoq', 'xintq', 'xoprq', 'xsgaq']

# Erstelle eine neue Tabelle, indem du nur die gewünschten Spalten kopierst
new_df = df_fundq_raw[columns_to_copy].copy()

new_df.to_csv("data/raw_features.csv")

In [22]:
feature_data_raw = pd.read_csv("data/raw_features.csv")
feature_data_raw.set_index(feature_data_raw.columns[0], inplace=True)
feature_data_raw

,gvkey,fyearq,fqtr,atq,saleq,mkvaltq,ibcomq,oiadpq,prccq,prchq,...,rllq,saleq.1,seqq,teqq,tieq,txtq,xidoq,xintq,xoprq,xsgaq
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
90,1003,1989,1.0,NaN,5.194,NaN,-0.753,-0.523,0.7500,1.75,...,NaN,5.194,NaN,NaN,NaN,0.00,0.000,0.230,5.717,2.153
91,1003,1989,2.0,13.328,4.384,2.012250,0.415,-0.755,0.7500,0.75,...,NaN,4.384,1.801,NaN,NaN,-1.37,2.333,0.200,5.139,2.067
92,1003,1989,3.0,NaN,4.776,2.012250,-0.613,-0.475,0.7500,0.75,...,NaN,4.776,NaN,NaN,NaN,0.00,0.000,0.138,5.251,2.304
93,1003,1989,4.0,10.109,4.913,2.012250,-1.603,-0.569,0.1250,0.75,...,NaN,4.913,-0.416,NaN,NaN,0.00,0.000,0.134,5.482,2.392
94,1003,1990,1.0,8.754,3.506,0.293789,-0.828,-0.710,0.1095,NaN,...,NaN,3.506,-1.244,NaN,NaN,0.00,0.000,0.118,4.216,2.049
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1965872,345980,2020,4.0,2397.000,794.000,15746.275000,-569.000,-511.000,18.2400,24.75,...,NaN,794.000,1027.000,1027.000,NaN,1.00,0.000,NaN,1302.000,963.000
1965972,351038,2020,1.0,NaN,595.500,8043.858240,NaN,NaN,18.2400,NaN,...,NaN,595.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1965973,351038,2020,2.0,NaN,397.000,5380.836480,NaN,NaN,18.2400,NaN,...,NaN,397.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1965974,351038,2020,3.0,NaN,198.500,2717.814720,NaN,NaN,18.2400,NaN,...,NaN,198.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1965975,351038,2020,4.0,1.378,0.000,54.792960,-2.095,-1.670,18.2400,NaN,...,NaN,0.000,-6.607,-6.607,NaN,0.00,0.000,0.047,1.566,1.566

In [23]:
feature_data_raw[['atq', 'saleq', 'mkvaltq', 'ibcomq', 'oiadpq', 'prccq', 'prchq', 'prclq', 'apq', 'capsq', 'cheq', 'csh12q', 'cshfdq', 'cshoq', 'cshprq', 'cshtrq', 'cstkq', 'dpq', 'dvpq', 'dvpsxq', 'epsf12', 'epsfiq', 'epsfxq', 'epspiq', 'epspxq', 'epsx12', 'ibq', 'icaptq', 'loq', 'lseq', 'ltq', 'mibq', 'mibtq', 'miiq', 'ncoq', 'niq', 'nopiq', 'oibdpq', 'piq', 'pllq', 'ppentq', 'pstkq', 'rectq', 'req', 'rllq', 'saleq', 'seqq', 'teqq', 'tieq', 'txtq', 'xidoq', 'xintq', 'xoprq', 'xsgaq']] = feature_data_raw[['atq', 'saleq', 'mkvaltq', 'ibcomq', 'oiadpq', 'prccq', 'prchq', 'prclq', 'apq', 'capsq', 'cheq', 'csh12q', 'cshfdq', 'cshoq', 'cshprq', 'cshtrq', 'cstkq', 'dpq', 'dvpq', 'dvpsxq', 'epsf12', 'epsfiq', 'epsfxq', 'epspiq', 'epspxq', 'epsx12', 'ibq', 'icaptq', 'loq', 'lseq', 'ltq', 'mibq', 'mibtq', 'miiq', 'ncoq', 'niq', 'nopiq', 'oibdpq', 'piq', 'pllq', 'ppentq', 'pstkq', 'rectq', 'req', 'rllq', 'saleq', 'seqq', 'teqq', 'tieq', 'txtq', 'xidoq', 'xintq', 'xoprq', 'xsgaq']].interpolate()
feature_data_raw

,gvkey,fyearq,fqtr,atq,saleq,mkvaltq,ibcomq,oiadpq,prccq,prchq,...,rllq,saleq.1,seqq,teqq,tieq,txtq,xidoq,xintq,xoprq,xsgaq
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
90,1003,1989,1.0,NaN,5.194,NaN,-0.75300,-0.5230,0.7500,1.750,...,NaN,5.194,NaN,NaN,NaN,0.00,0.000,0.23000,5.7170,2.1530
91,1003,1989,2.0,13.3280,4.384,2.012250,0.41500,-0.7550,0.7500,0.750,...,NaN,4.384,1.80100,NaN,NaN,-1.37,2.333,0.20000,5.1390,2.0670
92,1003,1989,3.0,11.7185,4.776,2.012250,-0.61300,-0.4750,0.7500,0.750,...,NaN,4.776,0.69250,NaN,NaN,0.00,0.000,0.13800,5.2510,2.3040
93,1003,1989,4.0,10.1090,4.913,2.012250,-1.60300,-0.5690,0.1250,0.750,...,NaN,4.913,-0.41600,NaN,NaN,0.00,0.000,0.13400,5.4820,2.3920
94,1003,1990,1.0,8.7540,3.506,0.293789,-0.82800,-0.7100,0.1095,0.422,...,NaN,3.506,-1.24400,NaN,NaN,0.00,0.000,0.11800,4.2160,2.0490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1965872,345980,2020,4.0,2397.0000,794.000,15746.275000,-569.00000,-511.0000,18.2400,24.750,...,8.6,794.000,1027.00000,1027.00000,2.126,1.00,0.000,0.60600,1302.0000,963.0000
1965972,351038,2020,1.0,1798.0945,595.500,8043.858240,-427.27375,-383.6675,18.2400,24.750,...,8.6,595.500,768.59825,768.59825,2.126,0.75,0.000,0.46625,976.8915,722.6415
1965973,351038,2020,2.0,1199.1890,397.000,5380.836480,-285.54750,-256.3350,18.2400,24.750,...,8.6,397.000,510.19650,510.19650,2.126,0.50,0.000,0.32650,651.7830,482.2830
1965974,351038,2020,3.0,600.2835,198.500,2717.814720,-143.82125,-129.0025,18.2400,24.750,...,8.6,198.500,251.79475,251.79475,2.126,0.25,0.000,0.18675,326.6745,241.9245
1965975,351038,2020,4.0,1.3780,0.000,54.792960,-2.09500,-1.6700,18.2400,24.750,...,8.6,0.000,-6.60700,-6.60700,2.126,0.00,0.000,0.04700,1.5660,1.5660

In [24]:
berechnungen_feature_set2 ={
    'mkvaltq':  ['sd dif', 'sd yoy', 'vwmean dif', 'mean dif', 'vwmean yoy', 'mean yoy'],
    'PRCCQ':    ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'PRCHQ':    ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'PRCLQ':    ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy']
}

In [25]:
berechnungen_feature_set3 = {
    'APQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'CAPSQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'CHEQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'CSH12Q': ['mean_dif', 'sd_yoy', 'sd_dif', 'mean_yoy', 'vwmean_dif'],
    'CSHFDQ': ['sd_dif', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'CSHOQ': ['sd_dif', 'vwmean_dif', 'mean_dif', 'mean_yoy', 'sd_yoy'],
    'CSHPRQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'CSHTRQ': ['sd_dif', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'CSTKQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'DPQ': ['vwmean_yoy', 'mean_yoy'],
    'DVPQ': ['sd_yoy', 'vwmean_yoy', 'mean_yoy'],
    'DVPSXQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'EPSF12': ['sd_dif', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'EPSFIQ': ['sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'EPSFXQ': ['sd_dif', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'EPSPIQ': ['sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'EPSPXQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'EPSX12': ['sd_dif', 'mean_dif', 'vwmean_yoy', 'sd_yoy', 'vwmean_dif', 'mean_yoy'],
    'IBQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'ICAPTQ': ['sd_dif', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'LOQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'LSEQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'LTQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'MIBQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'MIBTQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'MIIQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'NCOQ': ['vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'NIQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'NOPIQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'OIBDPQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'PIQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'PLLQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'PPENTQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'PSTKQ': ['sd_yoy', 'vwmean_yoy', 'mean_yoy'],
    'RECTQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'REQ': ['sd_dif', 'vwmean_yoy', 'mean_yoy', 'sd_yoy', 'vwmean_dif', 'mean_dif'],
    'RLLQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'SALEQ': ['mean_yoy', 'sd_dif', 'mean_dif', 'vwmean_yoy', 'vwmean_dif', 'sd_yoy'],
    'SEQQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'TEQQ': ['vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'TIEQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'TXTQ': ['vwmean_yoy', 'sd_yoy', 'sd_dif', 'mean_dif', 'vwmean_dif', 'mean_yoy'],
    'XIDOQ': ['sd_yoy', 'vwmean_yoy', 'sd_dif', 'mean_dif', 'vwmean_dif', 'mean_yoy'],
    'XINTQ': ['vwmean_yoy', 'mean_yoy'],
    'XOPRQ': ['sd_dif', 'sd_yoy', 'vwmean_dif', 'mean_dif', 'vwmean_yoy', 'mean_yoy'],
    'XSGAQ': ['mean_dif', 'vwmean_dif', 'vwmean_yoy', 'sd_yoy', 'mean_yoy', 'sd_dif']
}

In [26]:
# Compute Variants for feature set 2
# DataFrame für die neuen Werte
df_feature_set_2_calculated = pd.DataFrame()

# Berechnung der spezifizierten Wachstumsmaße für jede Variable
for variable, calculations in tqdm(berechnungen_feature_set2.items()):
    if 'sd_dif' in calculations:
        # Standardabweichung der Quarter-over-Quarter growth rate ("sd_dif")
        if f'{variable.lower()}_dif' not in feature_data_raw.columns:
           feature_data_raw[f'{variable.lower()}_dif'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff()
        df_feature_set_2_calculated[f'{variable.lower()}_sd_dif'] = feature_data_raw.groupby(['fyearq', 'fqtr'])[f'{variable.lower()}_dif'].std()

    if 'sd_yoy' in calculations:
        # Standardabweichung der Year-over-Year growth rate ("sd_yoy")
        if f'{variable.lower()}_yoy' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_yoy'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff(4)
        df_feature_set_2_calculated[f'{variable.lower()}_sd_yoy'] = feature_data_raw.groupby(['fyearq', 'fqtr'])[f'{variable.lower()}_yoy'].std()

    if 'vwmean_dif' in calculations:
        # Value-weighted average der Quarter-over-Quarter growth rate ("vwmean_dif")
        if f'{variable.lower()}_dif' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_dif'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff()
        feature_data_raw[f'{variable.lower()}_dif_mkvaltq'] = (feature_data_raw[f'{variable.lower()}_dif'] * feature_data_raw['mkvaltq'])
        df_feature_set_2_calculated[f'{variable.lower()}_vwmean_dif'] = feature_data_raw.groupby(['fyearq', 'fqtr'])[f'{variable.lower()}_dif_mkvaltq'].sum()/feature_data_raw.groupby(['fyearq', 'fqtr'])['mkvaltq'].sum()

    if 'mean_dif' in calculations:
        # Cross-sectional equal-weighted average der Quarter-over-Quarter growth rate ("mean_dif")
        if f'{variable.lower()}_dif' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_dif'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff()
        df_feature_set_2_calculated[f'{variable.lower()}_mean_dif'] = feature_data_raw.groupby(['fyearq', 'fqtr'])[f'{variable.lower()}_dif'].mean()

    if 'vwmean_yoy' in calculations:
        # Value-weighted average der Year-over-Year growth rate ("vwmean_yoy")
        if f'{variable.lower()}_yoy' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_yoy'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff(4)
        feature_data_raw[f'{variable.lower()}_yoy_mkvaltq'] = (feature_data_raw[f'{variable.lower()}_yoy'] * feature_data_raw['mkvaltq'])
        df_feature_set_2_calculated[f'{variable.lower()}_vwmean_yoy'] = feature_data_raw.groupby(['fyearq', 'fqtr'])[f'{variable.lower()}_yoy_mkvaltq'].sum()/feature_data_raw.groupby(['fyearq', 'fqtr'])['mkvaltq'].sum()

    if 'mean_yoy' in calculations:
        # Cross-sectional equal-weighted average der Year-over-Year growth rate ("mean_yoy")
        if f'{variable.lower()}_yoy' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_yoy'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff(4)
        df_feature_set_2_calculated[f'{variable.lower()}_mean_yoy'] = feature_data_raw.groupby(['fyearq', 'fqtr'])[f'{variable.lower()}_yoy'].mean()

# Zeige das aktualisierte DataFrame für Feature Set 3 an
df_feature_set_2_calculated.to_csv("data/feature_sets/feature_set_2_calculated.csv")
df_feature_set_2_calculated

100%|██████████| 4/4 [00:17<00:00,  4.43s/it]

             prccq_sd_dif  prccq_sd_yoy  prccq_vwmean_dif  prccq_mean_dif  \
fyearq fqtr
1989   1.0            NaN           NaN          0.000000             NaN
       2.0      19.519145           NaN          1.688910        0.380724
       3.0      31.304590           NaN          3.915837        0.206428
       4.0      21.423680      4.969442         -5.525103       -0.847429
1990   1.0      31.167222     63.077370         -4.803521       -1.096444
...                   ...           ...               ...             ...
2019   4.0      24.039349     63.296738         12.848948        0.932771
2020   1.0     121.280550     98.762191         -9.755619       -7.195372
       2.0      38.659753    113.310113         42.010874        2.983249
       3.0      25.948497    147.179492         15.349201        0.907388
       4.0      55.242283    136.876397        -14.887568        4.026264

             prccq_vwmean_yoy  prccq_mean_yoy  prchq_sd_dif  prchq_sd_yoy  \
fyearq fqtr
1989   1.0           0.000000             NaN           NaN           NaN
       2.0           0.000000             NaN     23.344245           NaN
       3.0           0.000000             NaN     29.402914           NaN
       4.0          -0.007820       -1.014078     22.392271      4.416269
1990   1.0           6.240684       -1.298114     22.748229     75.316275
...                       ...             ...           ...           ...
2019   4.0          36.420574        3.839770     26.230569    129.052062
2020   1.0          13.592352       -5.604409     18.923923     59.046947
       2.0          49.137211       -2.725603    127.236426    111.059471
       3.0          71.500903       -2.289075     30.560659    171.706745
       4.0          50.697865        1.463988     54.493935    142.130542

             prchq_vwmean_dif  prchq_mean_dif  prchq_vwmean_yoy  \
fyearq fqtr
1989   1.0           0.000000             NaN          0.000000
       2.0           2.400871        0.509431          0.000000
       3.0           3.262516        0.203681          0.000000
       4.0          -4.580357       -0.527874         -0.005366
1990   1.0          -1.366178       -1.007920         11.018646
...                       ...             ...               ...
2019   4.0           2.149701        0.106782         10.755160
2020   1.0          24.118606        1.157724         43.520680
       2.0          16.814683       -3.755461         52.248046
       3.0          30.610008        0.947796         84.342305
       4.0         -25.264790        2.880727         62.744117

             prchq_mean_yoy  prclq_sd_dif  prclq_sd_yoy  prclq_vwmean_dif  \
fyearq fqtr
1989   1.0              NaN           NaN           NaN          0.000000
       2.0              NaN      7.186760           NaN         -0.012133
       3.0              NaN     27.802759           NaN          3.433845
       4.0        -0.727536     26.916739      3.562137         -2.475928
1990   1.0        -0.739617     26.917069     61.834720         -3.153440
...                     ...           ...           ...               ...
2019   4.0        -0.514972     29.368189     57.450053          4.114298
2020   1.0         2.805078    121.064537    102.095007        -20.141144
       2.0        -1.295934     33.025128    121.318830         17.020607
       3.0        -1.453763     46.133331    117.969462         45.705678
       4.0         1.979972     41.875962    152.959278         -8.935583

             prclq_mean_dif  prclq_vwmean_yoy  prclq_mean_yoy
fyearq fqtr
1989   1.0              NaN          0.000000             NaN
       2.0         0.188473          0.000000             NaN
       3.0         0.218380          0.000000             NaN
       4.0        -0.492571         -0.003811       -0.670410
1990   1.0        -0.944337          6.764614       -1.000707
...                     ...               ...             ...
2019   4.0         0.376826         28.920279        2.153673
2020   1.0        -8.148914          5.763731       -6.277897
       2.0         1.262177          9.804874       -6.358028
       3.0         3.548697         50.461587       -2.822255
       4.0         1.257690         38.021840       -1.541951

[128 rows x 18 columns]

In [27]:
# Compute Variants for feature set 3
# DataFrame für die neuen Werte
df_feature_set_3_calculated = pd.DataFrame()

# Berechnung der spezifizierten Wachstumsmaße für jede Variable
for variable, calculations in tqdm(berechnungen_feature_set3.items()):
    if 'sd_dif' in calculations:
        # Standardabweichung der Quarter-over-Quarter growth rate ("sd_dif")
        if f'{variable.lower()}_dif' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_dif'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff()
        if f'{variable.lower()}_dif_atq' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_dif_atq'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff() / feature_data_raw['atq']
        if f'{variable.lower()}_dif_saleq' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_dif_saleq'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff() / feature_data_raw['saleq']

        df_feature_set_3_calculated[f'{variable.lower()}_sd_dif'] = feature_data_raw.groupby(['fyearq', 'fqtr'])[f'{variable.lower()}_dif'].std()


    if 'sd_yoy' in calculations:
        # Standardabweichung der Year-over-Year growth rate ("sd_yoy")
        if f'{variable.lower()}_yoy' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_yoy'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff(4)
        if f'{variable.lower()}_yoy_atq' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_yoy_atq'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff(4) / feature_data_raw['atq']
        if f'{variable.lower()}_yoy_saleq' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_yoy_saleq'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff(4) / feature_data_raw['saleq']

        df_feature_set_3_calculated[f'{variable.lower()}_sd_yoy'] = feature_data_raw.groupby(['fyearq', 'fqtr'])[f'{variable.lower()}_yoy'].std()


    if 'vwmean_dif' in calculations:
        # Value-weighted average der Quarter-over-Quarter growth rate ("vwmean_dif")
        if f'{variable.lower()}_dif' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_dif'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff()
        if f'{variable.lower()}_dif_atq' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_dif_atq'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff() / feature_data_raw['atq']
        if f'{variable.lower()}_dif_saleq' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_dif_saleq'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff() / feature_data_raw['saleq']

        feature_data_raw[f'{variable.lower()}_dif_mkvaltq'] = (feature_data_raw[f'{variable.lower()}_dif'] * feature_data_raw['mkvaltq'])
        df_feature_set_3_calculated[f'{variable.lower()}_vwmean_dif'] = feature_data_raw.groupby(['fyearq', 'fqtr'])[f'{variable.lower()}_dif_mkvaltq'].sum()/feature_data_raw.groupby(['fyearq', 'fqtr'])['mkvaltq'].sum()


    if 'mean_dif' in calculations:
        # Cross-sectional equal-weighted average der Quarter-over-Quarter growth rate ("mean_dif")
        if f'{variable.lower()}_dif' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_dif'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff()
        if f'{variable.lower()}_dif_atq' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_dif_atq'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff() / feature_data_raw['atq']
        if f'{variable.lower()}_dif_saleq' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_dif_saleq'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff() / feature_data_raw['saleq']

        df_feature_set_3_calculated[f'{variable.lower()}_mean_dif'] = feature_data_raw.groupby(['fyearq', 'fqtr'])[f'{variable.lower()}_dif'].mean()


    if 'vwmean_yoy' in calculations:
        # Value-weighted average der Year-over-Year growth rate ("vwmean_yoy")
        if f'{variable.lower()}_yoy' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_yoy'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff(4)
        if f'{variable.lower()}_yoy_atq' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_yoy_atq'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff(4) / feature_data_raw['atq']
        if f'{variable.lower()}_yoy_saleq' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_yoy_saleq'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff(4) / feature_data_raw['saleq']

        feature_data_raw[f'{variable.lower()}_yoy_mkvaltq'] = (feature_data_raw[f'{variable.lower()}_yoy'] * feature_data_raw['mkvaltq'])
        df_feature_set_3_calculated[f'{variable.lower()}_vwmean_yoy'] = feature_data_raw.groupby(['fyearq', 'fqtr'])[f'{variable.lower()}_yoy_mkvaltq'].sum()/feature_data_raw.groupby(['fyearq', 'fqtr'])['mkvaltq'].sum()


    if 'mean_yoy' in calculations:
        # Cross-sectional equal-weighted average der Year-over-Year growth rate ("mean_yoy")
        if f'{variable.lower()}_yoy' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_yoy'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff(4)
        if f'{variable.lower()}_yoy_atq' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_yoy_atq'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff(4) / feature_data_raw['atq']
        if f'{variable.lower()}_yoy_saleq' not in feature_data_raw.columns:
            feature_data_raw[f'{variable.lower()}_yoy_saleq'] = feature_data_raw.groupby('gvkey')[f'{variable.lower()}'].diff(4) / feature_data_raw['saleq']

        df_feature_set_3_calculated[f'{variable.lower()}_mean_yoy'] = feature_data_raw.groupby(['fyearq', 'fqtr'])[f'{variable.lower()}_yoy'].mean()


# Zeige das aktualisierte DataFrame für Feature Set 3 an
df_feature_set_3_calculated.to_csv("data/feature_sets/feature_set_3_calculated.csv")
df_feature_set_3_calculated

100%|██████████| 46/46 [11:51<00:00, 15.46s/it]

              apq_sd_dif   apq_sd_yoy  apq_vwmean_dif  apq_mean_dif  \
fyearq fqtr
1989   1.0           NaN          NaN        0.000000           NaN
       2.0    901.335416          NaN      -52.320109    -26.281858
       3.0    922.499860          NaN       53.374532    -21.289743
       4.0    927.719642    12.561790      179.214321    -15.961623
1990   1.0    624.558979  3177.856830      -64.796960    -17.631554
...                  ...          ...             ...           ...
2019   4.0   2147.021282  2594.816617     1199.242186     33.340228
2020   1.0   4224.683148  5955.683507     4336.973442    157.516577
       2.0   2311.907486  7426.060695     1748.086343    103.308743
       3.0   1043.036581  7571.838981     1048.329277     29.512946
       4.0   2672.229445  9060.890321     2961.261339     82.916800

             apq_vwmean_yoy  apq_mean_yoy  capsq_sd_dif  capsq_sd_yoy  \
fyearq fqtr
1989   1.0         0.000000           NaN           NaN           NaN
       2.0         0.000000           NaN    381.522611           NaN
       3.0         0.000000           NaN    370.211646           NaN
       4.0         0.031354      3.924847    386.535534      7.943031
1990   1.0       117.138466    -83.044219     63.147302   1147.746848
...                     ...           ...           ...           ...
2019   4.0      2493.044653    122.991803    677.638890   1299.742728
2020   1.0      6346.823319    251.802537    425.480999   1337.167493
       2.0      7987.846236    339.518169    408.865624   1151.631845
       3.0      8384.826054    338.707552    295.309841    964.808214
       4.0      8166.792547    395.485669    560.126852    848.193711

             capsq_vwmean_dif  capsq_mean_dif  ...  xoprq_vwmean_dif  \
fyearq fqtr                                    ...
1989   1.0           0.000000             NaN  ...          0.000000
       2.0         -96.237891      -20.050007  ...        101.678560
       3.0         -77.147492      -17.853621  ...        -56.031159
       4.0         -52.379585      -15.110756  ...        264.831045
1990   1.0         -11.545568       -0.843448  ...       -168.187564
...                       ...             ...  ...               ...
2019   4.0         393.519948       14.074475  ...       1113.883747
2020   1.0         195.511083       12.042204  ...        -77.940904
       2.0         440.997827       16.767815  ...       -671.976033
       3.0         297.619833       18.455561  ...        435.469450
       4.0         768.364443       27.943496  ...       2028.669034

             xoprq_mean_dif  xoprq_vwmean_yoy  xoprq_mean_yoy  xsgaq_sd_dif  \
fyearq fqtr
1989   1.0              NaN          0.000000             NaN           NaN
       2.0         3.707840          0.000000             NaN     30.035355
       3.0        -0.780296          0.000000             NaN     29.399768
       4.0        11.801106          0.019645        3.613921     36.100695
1990   1.0       -11.361143        140.221819        1.929310     40.131260
...                     ...               ...             ...           ...
2019   4.0        25.902268        688.944749       11.019481     77.683109
2020   1.0       -24.400975       1177.031448       16.998803     97.141856
       2.0       -36.811097        601.388469      -34.693335     75.553160
       3.0        20.456760        964.964089      -15.118283     54.277749
       4.0        38.050378       1594.079063       -1.456407    116.028788

             xsgaq_sd_yoy  xsgaq_vwmean_dif  xsgaq_mean_dif  xsgaq_vwmean_yoy  \
fyearq fqtr
1989   1.0            NaN          0.000000             NaN          0.000000
       2.0            NaN         18.166209       -0.665318          0.000000
       3.0            NaN          6.598938       -0.922319          0.000000
       4.0      12.704255         49.937089        0.710723          0.000377
1990   1.0     106.566082        -44.522331       -2.654924         30.377475
...                   ...               ...             ...               ...
2019   4.0     180.794929        308.962820        6.325520        354.035720
2020   1.0     131.400266       -206.105281       -6.816799        373.022742
       2.0     133.865696        106.792807       -2.655511        340.069755
       3.0     121.655461        138.831665        3.459572        367.386136
       4.0     160.368675        446.815632        9.079522        570.984088

             xsgaq_mean_yoy
fyearq fqtr
1989   1.0              NaN
       2.0              NaN
       3.0              NaN
       4.0        -5.012548
1990   1.0        -3.685760
...                     ...
2019   4.0         4.039635
2020   1.0         2.714064
       2.0        -2.554501
       3.0         0.519639
       4.0         3.635572

[128 rows x 249 columns]